name: github pages

on:
  push:
    branches:
      - DocFX

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: ./docs/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.NUGET_PAT }} # See https://github.com/maxheld83/ghpages   
