name: NuGet Package
on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/Digitalroot.CMB.RepositoryLoader/**'   
      - '.github/workflows/**'   
jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    env:
      PROJECT_PATH: Digitalroot.CMB.RepositoryLoader
      PROJECT_FILE_NAME: Digitalroot.CMB.RepositoryLoader.csproj
      SLN_FILE_NAME: Digitalroot.CustomMonoBehaviours.sln
      NUSPEC: Digitalroot.CustomMonoBehaviours.nuspec
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.1
        with:
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Restore packages
        run: nuget restore src/${{ env.SLN_FILE_NAME }}
      - name: Build
        run: dotnet build src/${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE_NAME }} -c Release
      - name: Publish
        run: nuget push ${{ github.workspace }}\src\${{ env.PROJECT_PATH }}\bin\Release\Digitalroot.CustomMonoBehaviours.1.0.0.nupkg -SkipDuplicate

