name: NuGet Package
on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/Digitalroot.CMB.RepositoryLoader/**'      
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      PATH: Digitalroot.CMB.RepositoryLoader
      NUSPEC: Digitalroot.CustomMonoBehaviours.nuspec           
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.1
        with:
          #dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Create the package
        run: nuget.exe pack src/$PATH/$NUSPEC -OutputDirectory ./bin/Release -Build -Properties Configuration=Release
      - name: Publish package to Digitalroot-Valheim nuget repository
        run: dotnet nuget push src/$PATH/bin/Release/*.nupkg --skip-duplicate
